version: "3"
services:
  elastic:
    container_name: elastic-compose-2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
        discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
  app:
    container_name: golang-rest-compose-2
    image: golang-rest:1.0
    environment:
        ELASTIC_HOST: elastic
        ELASTIC_PORT: 9200
    ports:
      - 9090:9090      