version: "3"
services:
  elastic:
    container_name: elastic-compose-2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
        discovery.type: single-node
    networks:
      edge:        
    ports:
      - 9200:9200
      - 9300:9300
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ELASTIC_HOST: proxy-elastic
      ELASTIC_PORT: 10000
      #ELASTIC_HOST: elastic
      #ELASTIC_PORT: 9200         
    networks:
      edge:
    ports:
      - 9090:9090

  proxy-elastic:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    networks:
      edge:
    ports:
      - "10000:10000"
      - "9901:9901"

networks:
  edge:
    name: edge